export const SETUSERNAME = "SETUSERNAME";
export const SETGAMESTATUS = "SETGAMESTATUS";
export const SETDIFFICULTY = "SETDIFFICULTY";
export const CALCSCORE = "CALCSCORE";
export const ADDATTEMPT = "ADDATTEMPT";
export const SETTIME = "SETTIME";
export const RESETGAME = "RESETGAME";

export const ADDSCORETOSCOREBOARD = "ADDSCORETOSCOREBOARD";
